# Generated by Django 3.1.1 on 2020-10-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Portfolio',
        ),
    ]
