# Generated by Django 3.1.1 on 2020-10-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201026_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Portfolios',
        ),
    ]
