# Generated by Django 3.1.1 on 2020-11-03 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_auto_20201028_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='author',
        ),
        migrations.AddField(
            model_name='portfolios',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
