# Generated by Django 3.1.1 on 2020-11-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolios_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='image',
            field=models.ImageField(null='True', upload_to='portfolio'),
            preserve_default='True',
        ),
    ]
