# Generated by Django 3.1.1 on 2020-11-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolios_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='myClass_in_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
    ]
