# Generated by Django 3.1.1 on 2020-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201111_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass_in_model',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='myclass_in_model',
            name='pbs',
            field=models.TextField(null=True),
        ),
    ]
