# Generated by Django 3.1.1 on 2020-11-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20201111_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myclass_in_model',
            old_name='name',
            new_name='aum',
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='annual_perf',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='cum_perf',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='first_inv_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='fund_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='june_perf',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='m_str',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='nav',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='pday_perf',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='perf_2019',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='std',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='week_perf',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
