# Generated by Django 3.1.1 on 2020-11-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20201114_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myclass_in_model',
            old_name='aum',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='myclass_in_model',
            old_name='first_inv_date',
            new_name='initial_date',
        ),
        migrations.RenameField(
            model_name='myclass_in_model',
            old_name='m_str',
            new_name='m_strategy',
        ),
        migrations.RenameField(
            model_name='myclass_in_model',
            old_name='nav',
            new_name='modified_base',
        ),
        migrations.RenameField(
            model_name='myclass_in_model',
            old_name='std',
            new_name='setting',
        ),
        migrations.RenameField(
            model_name='myclass_in_model',
            old_name='annual_perf',
            new_name='year_conv_perf',
        ),
        migrations.AddField(
            model_name='myclass_in_model',
            name='total_net_profit',
            field=models.TextField(null=True),
        ),
    ]
