# Generated by Django 3.1.1 on 2020-11-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20201124_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myClass_in_model',
            new_name='Samofund',
        ),
    ]
